# We need this GitHub action to create a JitPack snapshot
name: Auto Tag "dev" branch

on:
  push:
    branches:
      - dev

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required to push tags

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required to create tags

      - name: Get Maven project version
        id: maven_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          TAG="${{ steps.maven_version.outputs.VERSION }}-${{ github.run_number }}-$(git rev-parse --short HEAD)"
          echo "Tagging with $TAG"
          git tag "$TAG"
          git push origin "$TAG"