name: Auto Tag "dev" branch to create a JitPack snapshot

on:
  push:
    branches:
      - dev

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # required to push tags

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required to create tags

      - name: Create tag
        run: |
          TAG="dev-$(git rev-parse --short HEAD)"
          echo "Tagging with $TAG"
          git tag "$TAG"
          git push origin "$TAG"